name: Triage PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # - name: Assign author to PR
      #   if: github.event.action == 'opened'
      #   uses: technote-space/assign-author@v1.6.2

      - name: Label to PR
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/pr-labeler.yaml
